### ISSUE TITLE
enable 'import' to utilize publishSettings file

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/azurectl#10]
Add an import, ala
azure account import
and perhaps drag the file to ~/.azurectl/
the point is to make it easier to get started

**Comment by schaefi** [comment]
I was thinking about having an account import command but with regards how to download the publish settings file I still find not much value having this command because it will not prevent the step we have documented here:

https://github.com/SUSE/azure-cli#credentials

Once the publish settings file has been downloaded which requires you to manually login to the azure portal it seems pretty straight forward to create the config file as documented here:

https://github.com/SUSE/azure-cli#configuration-file

maybe an

```
azure config initialize
```

would make more sense, which would create a default config incuding information how to fill the gaps

Thoughts ?

**Comment by bear454** [comment]
Hmm... from the publishsettings file, we can poke into the API and get a list of storage accounts, and from there, containers. (We do it on Studio)

It would be possible to do a command that you pass the publishsettings to, then it asks which storage account to default to, and which container, and writes the config file.

That's a fair bit of work for a small file, though.

**Comment by rjschwei** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 05/06/2015 11:15 AM, James Mason wrote:
> Hmm... from the publishsettings file, we can poke into the API and
> get a list of storage accounts, and from there, containers. (We do
> it on Studio)
> 
> It would be possible to do a command that you pass the
> publishsettings to, then it asks which storage account to default
> to, and which container, and writes the config file.
> 
> That's a fair bit of work for a small file, though.

My thought was something along these lines

azurctl config add-account --name --settings-file --storage-account
- --container-name

We could then copy the publishsettingsfile from the location given to
~/.azurectl/publishsettings and simply add the newly added account to
the config file, after some consistency checks.

This should not be too much code and would be a nice feature, IMHO.


-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJVSkNRAAoJEE4FgL32d2UkAQAH/0zp2HCzRZbk6fHrNOLRrnLY
GZLzP7sAGgbyTmVl9sjmb0b7m4sGFhjs9jLjeafmgTB10qggMVY2s02oivhc9wm3
8GBUEicUxU46Zl7gjZCzEUwb+0KkjfxtdL2NyyAsgUavRgPPN+8c1Jw1KnOB6mD0
w49dNezGAJaEgeOdIIIr+v2qRw8yGYGFP6WxGSIPMtf1KFMl2qEr7kXmz2RXL1G3
2+34clfBcYqdsveUUaoouu7yoeq5r7z2wYoJoRqzn24XiiDqFt082rTWTxeuaMfw
vZRIwO5alvAd9fUy4X4MhxIoEFoeNHtqPZkcaoTnIt3idzaWv/koWriVoeiMQWY=
=HMFo
-----END PGP SIGNATURE-----

**Comment by schaefi** [comment]
>My thought was something along these lines…

>azurctl config add-account --name --settings-file --storage-account
>- --container-name

>We could then copy the publishsettingsfile from the location given to
>~/.azurectl/publishsettings and simply add the newly added account to
>the config file, after some consistency checks.

I would be ok with this

This should not be too much code and would be a nice feature, IMHO.

**Comment by schaefi** [comment]
working on this now
