### ISSUE TITLE
nosetests is not maintained

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#102]
Since the nose testing framework is no longer maintained, we should move to pytest.

**Comment by schaefi** [comment]
I have successfully tested

```
cd test/unit && py.test *.py
```

So transition from nosetests to pytest is not a problem, but is it true that python-nose is no longer maintained ? where do you see this information ?

@tomschr Do you know if nose will go away and what the preferred testing system for python and python3 is ?

Thanks

**Comment by tomschr** [comment]
@schaefi That's pity. As James already said, use [pytest](http://pytest.org). It's my main testing framework for Python 2 *and* Python 3. Both version works. It has lots of plugins to extend it.

Luckily, there is the section [Running tests written for nose](http://pytest.org/latest/nose.html) which should help to lower the pain. At least a bit. :grin:

Try it out and you will see it's really worth! I like it pretty much! :smiley:

**Comment by tomschr** [comment]
@schaefi Regarding maintenance, there is a note on its homepage:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

**Comment by bear454** [comment]
https://nose.readthedocs.org/en/latest/#note-to-users

James Mason
Technical Architect, Public Cloud
openSUSE Member
SUSE
jmason@suse.com

**Comment by schaefi** [comment]
working on this one now
