### ISSUE TITLE
config handling inconsistent

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#125]
> azurectl --version
azurectl version 1.8.1

After setting up an account with 

azurectl setup account configure --name 

a config file is created in ~/.config/azurectl/ with the name config. However using the just configured account fails with:

azurectl --account=updates compute storage.....
ERROR: AzureAccountLoadFailed: 'Could not find account config file: .config/azurectl/updates.config in home directory: /home/rjschwei'

**Comment by schaefi** [comment]
version 2.0.0 is out, I suggest you give that one a try to see if we still suffer from this

Thanks
