### ISSUE TITLE
azurectl 2.0 - config conflict

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#138]
Potential conflict of configuration. Prior to 2.0 all configuration was stored in 1 config file. With azurectl 2.0 we have 1 config file per account. It is now possible to create a configuration with conflicting information.

For example if I previously configured an account "foo" there exists and entry in .config/azurectl/config of 

[account:foo]
.....

It is now possible with azurectl 2.0 to run

azurectl setup account configure --name=foo --publish-settings-file=PATH

and generate a config/azurectl/foo.config file. Depending on the information I provide to the "account configure" command the previous configuration and the new configuration may be inconsistent or incompatible.

The user should get a warning, possibly error out, or the account from config should be converted to the new style when an attempt is made to create an account of the same name.

**Comment by schaefi** [comment]
How about the following change

When calling "azurectl setup account configure" that account will become the default account automatically ?

This will prevent any inconsistency in my eyes

Thoughts
