### ISSUE TITLE
azurctl 2.0 simply list the sub commands

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#139]
IMHO we should simply list the sub-commands when help is requested at the higher level. For example:

-> azurectl compute --help
INFO: Did you mean
INFO: --> azurectl compute data-disk
INFO: --> azurectl compute endpoint
INFO: --> azurectl compute image
INFO: --> azurectl compute request
INFO: --> azurectl compute reserved-ip
INFO: --> azurectl compute shell
INFO: --> azurectl compute vm

I think:

commands:
  data-disk
  endpoint
  image
  request
  reserved-ip
  shell
  vm

Would be a nicer output.

**Comment by schaefi** [comment]
I like the former output more, it's cut and paste capable

sorry I don't consider this an issue at all. I'm starting to think we are pretty nitpick. This is neither inconsistent nor wrong it's just an information and personal taste, which imho should not be considered an issue

**Comment by rjschwei** [comment]
Yes to a certain extend this is a "taste" issue. Further, IMHO we need to be nitpick.

Anyway:

-> azurectl compute --help
INFO: Did you mean
....

The answer to "Did you mean" is "no I simply wanted help" obviously I did not know any of the available sub commands. So another option to stay with the idea of cut and based would be:

-> azurectl compute --help
usage:
 azurectl compute data-disk
 azurectl compute endpoint
 azurectl compute image
 azurectl compute request
 azurectl compute reserved-ip
 azurectl compute shell
 azurectl compute vm

which would at least be consistent with the help message generated by other commands. When using 

azurectl compute data-disk --help

I actually get help instead of a smart alec suggestion that I really wanted something else. I get the "Did you mean" message when I type something wrong. In that context it is a helpfule message. But when I ask for help via --help I expect to receive it.

**Comment by schaefi** [comment]
I'm ok with the usage aspect, see the pr
