### ISSUE TITLE
Remove --create from setup

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#154]
While using "--create" may appear to be a convenience it is actually not and creates inconsistency in the implementation.

`setup account configure ... --storage-account-name=<storagename> --container-name=<containername> --create` is the same as
`storage account create --name=<accountname>`
`storage container create --name=<containername>`

However with the `storage account create` code path many more options exist. such as assigning a label or setting redundancy. Therefore the convenience implementation on the 'setup' command really presents a command inconsistency within azurectl. This is introduced because we support to do the same thing in multiple ways, which should not be done. The 'setup' command should be used to manipulate the local configuration, while other command have an effect on the user's resource state in Azure itself.

**Comment by schaefi** [comment]
We also allow updating of storage account and container metadata. Thus the workflow configure with
--create followed by storage account update is as valid as creating the storage account before the account configuration

I don't understand why we should delete a working feature we intentionally agreed to add for 2.0 ?

**Comment by schaefi** [comment]
I'm not going to rip that out for 2.0 and would rather continue with the release. If we'll find out nobody is using this feature we can easily drop it for a 3.0 release

**Comment by rjschwei** [comment]
On 05/11/2016 03:09 AM, Marcus Schäfer wrote:
> I'm not going to rip that out for 2.0 and would rather continue with the
> release. If we'll find out nobody is using this feature we can easily
> drop it for a 3.0 release

Fair enough, how are we going to remember to do this with the issue closed?


-- 
Robert Schweikert                   MAY THE SOURCE BE WITH YOU
Public Cloud Architect                         LINUX
rjschwei@suse.com
IRC: robjo

**Comment by schaefi** [comment]
>    Fair enough, how are we going to remember to do this with the issue
>    closed?

I'll open a card for it on the trello board

**Comment by schaefi** [comment]
For reference:

https://trello.com/c/F4RkzCmN/151-azurectl-storage-creation-on-account-configuration
