### ISSUE TITLE
region naming issue

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#160]
There is an internal issue with region name handling. For an an account that has "East Us" region configured:

azurectl compute vm create --cloud-service-name=a_name --image-name an_image_name --instance-name an_instance_name --password linux --user me

ERROR: AzureDomainLookupError: 'Specified region region:East US not in lookup table'

The "region:East Us" is suspicious as this is the way we handle names in the config file by using the "region:" prefix.

Command also fails when specifying the global "--region" argument

This may be related to a fix provided with 190eddde4f33 for another issue

**Comment by bear454** [comment]
`"East US" != "East Us"` Fix your config file.

**Comment by rjschwei** [comment]
On 05/06/2016 05:55 PM, James Mason wrote:
> `"East US" != "East Us"` Fix your config file.

Config file contains:

[region:East US]

??


-- 
Robert Schweikert                   MAY THE SOURCE BE WITH YOU
Public Cloud Architect                         LINUX
rjschwei@suse.com
IRC: robjo

**Comment by schaefi** [comment]
`Specified region region:East US not in lookup table` message seems to indicate that your region
name is set to `region:East US`, including the `region:` prefix. I have not found a way to come to
such a region name. 

ENOREPRODUCE

**Comment by bear454** [comment]
I can reproduce, but I had to rebuild the dev environment:

```
make clean
./setup.py develop
```

Then...

```
$   azurectl --region="Canada Central" compute vm create --image-name=b4590d9e3ed742e4a1d46e5424aa335e__suse-sles-12-sp1-v20160414 --cloud-service-name=JFM-ca-infra-test2 --ssh-private-key-file=/home/jmason/.ssh/azure.key --user=jmason --instance-type=Medium
ERROR: AzureConfigVariableNotFound: "default_storage_account not found: No section: 'Canada Central'"

$ grep 'Canada Central' -A3 ~/.config/azurectl/config 
[region:Canada Central]
default_storage_account = smtcanadacentral
default_storage_container = vm-images
```

**Comment by rjschwei** [comment]
account/setup.py

line 210: 
  section_name = 'region:' + section_name

Thus we add the "region:" prefix to the section name. This is in the "add_region" method. This section name is then used in a try block to create a section on the config object the code holds:

  self.config.add_section(section_name)

This would indicate that somewhere in the code we do not account for the prefix of "region:" when trying to access region information. This mismatch subsequently leads to the error message.

**Comment by bear454** [comment]
Yes, I'm debugging.
