### ISSUE TITLE
reserved-ip requiring storage_account

### ISSUE THREAD

**Issue by joelgordon** [SUSE/azurectl#166]
$azurectl --account=updates compute reserved-ip create --name='IP-SMT1-UK-North'

ERROR: AzureConfigVariableNotFound: "default_storage_account not found: 'No region referenced in configuration file /home/jgordon/.config/azurectl/updates.config'"

**Comment by schaefi** [comment]
I'm looking into that one

**Comment by bear454** [comment]
Should be the same kind of fix as for storage accounts.

**Comment by schaefi** [comment]
yes
