### ISSUE TITLE
differences in azurectl help

### ISSUE THREAD

**Issue by joelgordon** [SUSE/azurectl#193]
'azurectl compute data-disk help' and 'azurectl compute data-disk -h' return different information. 

It appears to me that the content of  'azurectl compute data-disk -h' has the current method of creating and attaching disks. At some point these command went from being 1 command to being 2.

**Comment by schaefi** [comment]
*argh* we missed to update the manual page

**Comment by bear454** [comment]
`attach` is also missing from the docopt commands list: https://github.com/SUSE/azurectl/blob/master/azurectl/commands/compute_data-disk.py#L40
