### ISSUE TITLE
race condition with the API

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#199]
When using the --wait option on instance creation we might trigger a race condition with the Azure API resulting in the following error message:

ERROR: AzureRequestStatusError: 'AzureHttpError: Bad Request\n<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The operation request ID was not found.</Message></Error>'

It appears that the request ID for the vm creation is returned by the API and azurectl then turns around and uses the returned ID to query the status. However, it appears that the Azure tables have not been updated by that time and thus an error condition is triggered. We should probably wait (sleep) for a little bit after we receive the request ID. Also we should re-try the operation before propagating the error to the user.

**Comment by schaefi** [comment]
Makes sense, yes. I'll look into it
