### ISSUE TITLE
Error reported after creation of image

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#22]
`azurectl compute image create` throws an error, after successfully completing the task:

```
ERROR: AzureOsImageCreateError: "AttributeError: 'AsynchronousOperationResult' object has no attribute 'get_operation_status'"
```

**Comment by schaefi** [comment]
Hrm, get_operation_status has been removed from the sdk, I'll take a look

**Comment by schaefi** [comment]
get_operation_status is in ServiceManagementService not in 'AsynchronousOperationResult'
I'll fix this

**Comment by schaefi** [comment]
James could you give it a try ?

Thanks
