### ISSUE TITLE
The tarball(s) need to be versioned

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#24]
When packaging the tool having tarballs that are not versioned creates an additional complication that is not necessary. It is much easier for packagers to have versioned tarballs as it is immediately obvious in the package build directory which version is being packaged.

**Comment by schaefi** [comment]
This is fixed now. In order to prevent actively closing fixed issue please do not use the indention style with [+.-] in your commit messages, and just write Fixes #id, github seems to be unable to notice the fix otherwise. Thanks
