### ISSUE TITLE
Look for an Additional Configuration File under ~/.config/azurectl/ (XDG)?

### ISSUE THREAD

**Issue by tomschr** [SUSE/azurectl#41]
In the "old" days, configuration files are stored directly under `$HOME` like `~/.bashrc`. There is nothing wrong with that approach.

However, it seems thesedays more and more applications store there configuration files under `~/.config`. This directory comes from the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

Maybe `azurectl` could look to find `~/.config/azurectl/config`first . If it fails, it could try it with `~/.azurectl/config`.

Just an idea. :smile:

**Comment by schaefi** [comment]
This could be certainly added. We are currently on hold with a release of azurectl to sles12 until Microsoft will release the new version of the SDK. This will happen in August. Once azurectl is publicly available we will see if there is demand for an alternative config file location

Does that sound fair to you ?

**Comment by tomschr** [comment]
Sure, absolutely! :+1:  Just an idea, not all my ideas are good. :wink:

**Comment by bear454** [comment]
I agree; we should change `azurectl` to default to `~/.config/azurectl/`, and since we have it, fall back to `~/.azurectl/`.  Thanks @tomschr for finding the spec for this.

**Comment by rjschwei** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 07/27/2015 01:47 PM, James Mason wrote:
> I agree; we should change `azurectl` to default to
> `~/.config/azurectl/`, and since we have it, fall back to
> `~/.azurectl/`.  Thanks @tomschr for finding the spec for this.
> 

If we go this direction, which is fine with me I would propose that we
move existing configuration files to the new location.

Thus we would:
- - look in ~, if we find the config file
  + move it to ~/.config/azurectl/ if there is no config file
  + merge with ~/.config/azurectl/ if a config file exists
    ~ do nothing if a merge is not possible, i.e. same accounts exist
      with different credentials
  + remove the config file from ~ after successful merge
- - create new files in ~/.config/azurectl/
- - deprecate the ~ location of the config and print a message
  + remove the merge code at a given date
  + remove the code that looks at ~ at the same date as the merge code



- -- 
Robert Schweikert                   MAY THE SOURCE BE WITH YOU
Public Cloud Architect                         LINUX
rjschwei@suse.com
IRC: robjo
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJVtnq0AAoJEE4FgL32d2UkTLAH/1PchTxWATA4gGqy3Khm0EW+
yev2zizjzdaZ+2a8kFH985PG22/CsXVvtAJSD7Q1h81IJ23t5Vs7SnWG2orhyhuo
YPTvMWV82h63Fn+XwOTd6y4OLmCJuDZUwyUqXrPcZz9jdeZoFnlgb3e9rqwvcB5v
NeKNXrcmrJ2PQX/i8SH6s69IQ90HrN9XpBkv11PqPEpC24GhFGqh3YB6cr6h7uqW
4zk56YtCcsYIZnMINtHQ++FNDtffo4IeBo49w31f2ZElYWsPEg0DDeaAdFLP9qPV
oEPh8T/JcyxS6Q35q4gpWr7BIL2+qzST6DrBMA8EDLYkHv4+9mHwnSBFd7qVBgQ=
=quAE
-----END PGP SIGNATURE-----

**Comment by schaefi** [comment]
Since we haven't released azurectl I would say we are still free to introduce a new location for the config file without taking care for backward compatibility to that extend

**Comment by schaefi** [comment]
@rjschwei if you haven't started to work on this one yet, I would do it today. please give me a short status. Thanks

**Comment by schaefi** [comment]
This is done now
