### ISSUE TITLE
Cannot setup accounts without having setup a [default] account.

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#48]
When setting up an account for the first time:

```
> azurectl setup account add \
> --name my-account \
> --publish-settings-file my.publishsettings \
> --storage-account-name some-storage-account \
> --container-name vhds
ERROR: AzureAccountNotFound: 'Account default not found'
```

This can also be reproduced on an existing account, by removing or renaming the `[default]` section in the config file.

**Comment by schaefi** [comment]
Uhm, shame on me not having tested that. I'll fix that as soon as possible

**Comment by bear454** [comment]
On Fri, 2015-09-18 at 10:59 -0700, Marcus Schäfer wrote:
> Uhm, shame on me not having tested that. I'll fix that as soon as
> possible
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/SUSE/azurectl/issues/48#issuecomment-141520422

I was going to take care of it, just wanted the PR on the file location
merged in first ;-)

-- 
James Mason
Technical Architect, Public Cloud
openSUSE Member
SUSE
jmason@suse.com
-------------------------------------
SUSECon 2015: Register at susecon.com

**Comment by schaefi** [comment]
That's good, thanks so I'll leave it in your hands. Yes let's wait for the config file move to be merged
