### ISSUE TITLE
'default' is not a valid name when adding an account to config...

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#51]
Found this while working on #48 : 
https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.add_section

**Comment by schaefi** [comment]
That basically means you can have only one default section. Is this a problem ?

If I call ./azurectl setup account add --name default ... I got

```
ERROR: AzureConfigAddAccountSectionError: 'ValueError: Invalid section name: default'
```

If I use another section name which also exists I got

```
ERROR: AzureConfigAddAccountSectionError: "DuplicateSectionError: Section 'sharetest' already exists"
```

So I think we are good if catch the ValueError on default and provide a better error message

Thoughts ?

**Comment by bear454** [comment]
Please explain how you would write the section named 'default' into the config file, for example, in the case of a new user.

**Comment by schaefi** [comment]
```
[default]
storage_account_name =
storage_container_name =
publishsettings =

[james]
storage_account_name =
storage_container_name =
publishsettings =

[marcus]
storage_account_name =
storage_container_name =
publishsettings =
```

I'm sure I'm missing the point ?

**Comment by bear454** [comment]
The point is, you cannot produce that '[default]' section using `azurectl setup account --name=default ...`.

**Comment by schaefi** [comment]
ok got it, will look into this today
