### ISSUE TITLE
Change meaning of --account option

### ISSUE THREAD

**Issue by schaefi** [SUSE/azurectl#60]
In an effort to maintain multiple configuration files the --account option should not select an account section in the config file but should select a config file from the default directory. Example

```
azurectl --account suse-rd
```

looks up

```
~/.config/azurectl/config.suse-rd
```

the loaded config file should only contain one account section which is referenced in the DEFAULT section.

**Comment by bear454** [comment]
IMO `suse-rd.config` is more conventional, as [description].[type] .

**Comment by schaefi** [comment]
yes makes sense, thanks. working on this now

**Comment by schaefi** [comment]
done now
