### ISSUE TITLE
better describe error condition for --cloud-service

### ISSUE THREAD

**Issue by rjschwei** [SUSE/azurectl#66]
The explanation for the --cloud-service needs to better describe the potential error condition.

**Comment by schaefi** [comment]
for the record, on creating a cloud service the following error message could appear

```
<Message>
       The specified DNS name is already taken
</Message>
```

This is because the cloud service name is used as DNS name for the instance

The message doesn't make that part clear and we should provide some information in the manual page about it

**Comment by schaefi** [comment]
This will be handled with Issue #67
