### ISSUE TITLE
missing dependency on python-setuptools

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#80]
Upon installation on a clean system, first run outputs:

```
> azurectl 
Traceback (most recent call last):
  File "/usr/bin/azurectl", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

`pkg_resources` is provided by python-setuptools.

**Comment by rjschwei** [comment]
I am not fond of having setuptools as a runtime dependency. Makes me wonder if we should not change our approach and instead of letting setuptools  do the generation that triggers this dependency write the main entry point such that setuptools is not needed at runtime?

**Comment by bear454** [comment]
@rjschwei , @schaefi : now we have two different solutions, both with and without setuptools. Comments, please?

**Comment by schaefi** [comment]
as said in the pull request, I'd like to see us using python-setuptools

**Comment by schaefi** [comment]
Fixed
