### ISSUE TITLE
icon_uri attribute of image fails to update

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#85]
```
$ azurectl --account publish compute image update --name test-attributes --small-icon-uri "icon.png" --icon-uri "bigicon.png"
INFO: Updating image metadata for: test-attributes
INFO: --> small_icon_uri = icon.png
INFO: --> icon_uri = bigicon.png
ERROR: AzureOsImageUpdateError: 'The element(s) "icon_uri" could not be updated. Please check if your account is registered as image publisher'
```
All the other attributes, including `small_icon_uri` succeed in updated the image metadata; only `icon_uri` fails to update.

**Comment by schaefi** [comment]
Strange I guess we have to wait for Steve to respond to your mail

**Comment by bear454** [comment]
Did some more brute force work, and found an element order that does work; sorry for missing this one element the first time.  I'll submit an additional PR to the python-sdk .
