### ISSUE TITLE
Add a command for showing/monitoring replication progress.

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#89]
Image replication takes minutes to hours, and images cannot be published until replication is complete.

In order to know when an image can be published after replication, we need a command to show replication progress.  In powershell, the data is provided by the Get-AzurePlatformVMImage command.

We should be able to use the source API to provide the same functionality.

As a bonus, we could wrap it in a loop, that runs on a regular schedule until publishing is complete; if not, I can always use `watch`.

**Comment by bear454** [comment]
Here's the powershell script I've historically used for monitoring replication progress:

[replication.ps1.txt](https://github.com/SUSE/azurectl/files/99872/replication.ps1.txt)

**Comment by schaefi** [comment]
yes that makes sense. Just for my own understanding; azurectl's Image::replicate() method returns with a request status. This status can be queried by:

```
azurectl compute request wait --id <request-number>
```

waiting for the request to complete does not mean that the image is already available.
Is that correct ?

**Comment by bear454** [comment]
@schaefi I'd like to work on this, if you don't mind

**Comment by bear454** [comment]
I submitted supporting code upstream to the SDK: https://github.com/Azure/azure-sdk-for-python/pull/518

**Comment by bear454** [comment]
Merged upstream via https://github.com/Azure/azure-sdk-for-python/pull/519
