### ISSUE TITLE
Can't create two VMs from the same image in the same storage container

### ISSUE THREAD

**Issue by bear454** [SUSE/azurectl#99]
When instantiating a new VM, we create a disk file with the name '<image-name>_instance', in the selected storage container.

Since storage files have unique names, only one VM can created from the same image in a selected region and container.

See:

* https://github.com/SUSE/azurectl/blob/master/azurectl/compute_vm_task.py#L152
* https://github.com/SUSE/azurectl/blob/master/azurectl/virtual_machine.py#L137

**Comment by schaefi** [comment]
yes, I'll care for this one
